#!/bin/bash

# default settings
java_opts=()
opts=()
args=()
jar_path="$0.jar"
default_annotation_folder="$(dirname "$0")/AnnotationFilesComplete/"

# process arguments
while [ $# -gt 0 ]; do
	case "$1" in
		-cp|-classpath)
			java_opts+=("$1" "$2")
			shift
			;;
		-default_annotation_folder)
			default_annotation_folder="$2"
			shift
			;;
		-disable_test)
			opts+=("$1" "$2")
			shift
			;;
		-no_mutationfiles|-always_mutationfiles|-no_significance|-always_significance|-no_combine|-always_combine)
			opts+=("$1")
			;;
		-k)
			opts+=("$1")
			;;
		-jar_path)
			jar_path="$2"
			shift
			;;
		-seed=*)
			opts+=("$1")
			;;
		-z*)
			opts+=("$1")
			;;
		-*)
			java_opts+=("$1")
			;;
		*)
			args+=("$1")
			;;
	esac
	shift
done

# print usage
usage() {
	echo "Usage: $(basename "$0") [java-opts] [-k] [-z] entity path_file output_folder [annotation_folder]" >&2
	exit 1
}

# check usage
if   [ "${#args[@]}" -eq 3 ]; then
	args+=("$default_annotation_folder")
elif [ "${#args[@]}" -eq 4 ]; then
	:
else
	usage
fi

# let's go..
exec java "${java_opts[@]}" -jar "$jar_path" "${opts[@]}" "${args[@]}"
